# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(782, 546)
        mainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        mainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.folderPathSelector = QtWidgets.QPushButton(parent=self.centralwidget)
        self.folderPathSelector.setObjectName("folderPathSelector")
        self.horizontalLayout.addWidget(self.folderPathSelector)
        self.line_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.fileNameLable = QtWidgets.QLabel(parent=self.centralwidget)
        self.fileNameLable.setObjectName("fileNameLable")
        self.horizontalLayout.addWidget(self.fileNameLable)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.amountLable = QtWidgets.QLabel(parent=self.centralwidget)
        self.amountLable.setObjectName("amountLable")
        self.horizontalLayout.addWidget(self.amountLable)
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.catAddLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.catAddLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.catAddLineEdit.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.catAddLineEdit.setText("")
        self.catAddLineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.catAddLineEdit.setPlaceholderText("")
        self.catAddLineEdit.setObjectName("catAddLineEdit")
        self.horizontalLayout.addWidget(self.catAddLineEdit)
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setMaximumSize(QtCore.QSize(45, 16777215))
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonsGrigLayout = QtWidgets.QGridLayout()
        self.buttonsGrigLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.buttonsGrigLayout.setSpacing(6)
        self.buttonsGrigLayout.setObjectName("buttonsGrigLayout")
        self.verticalLayout_2.addLayout(self.buttonsGrigLayout)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Image Sorter"))
        self.folderPathSelector.setText(_translate("mainWindow", "folderPath"))
        self.fileNameLable.setText(_translate("mainWindow", "FileName"))
        self.amountLable.setText(_translate("mainWindow", "TextLabel"))
        self.addButton.setText(_translate("mainWindow", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
